spring.application.name=hop2school

application:
app.name=${APPLICATION_NAME}
app.mail=${APPLICATION_MAIL}

api.key.geocoding=${GEOCODING_API_KEY}

jwt.secret=${JWT_SECRET}

spring.thymeleaf.cache=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true